version: "3.9"
services:
  postgres:
    container_name: gaugedb
    image: postgres:13.3
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD", "psql", $DATABASE_DSN]
        interval: 3s
        timeout: 1s
        retries: 5
    env_file: .env
  gaugeserver:
    container_name: gaugeserver
    image: gaugeserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    env_file: .env
  client:
    container_name: client
    image: client
    depends_on:
      gaugeserver:
        condition: service_started
    build:
      context: .
      dockerfile: cmd/agent/Dockerfile
    env_file: .env


